image:
  name: asia-southeast1-docker.pkg.dev/its-artifact-commons/utils/interface-manager
  tag: develop-32ad8cf

configs: {}
replica: 1

resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "200Mi"
    cpu: "150m"
