apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-soc-ing-legacy
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    kubernetes.io/ingress.class: "nginx"
spec:
  #tls:
  #  - hosts:
  #    - {{ .Values.domain }}
  #    #secretName: kibana-soc-cert-legacy
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: es-censor-kb-http
                port:
                  number: 5601
      #host: {{ .Values.domain }}
