apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alerts-webhook-01
  namespace: monitoring
spec:
  receivers:
  - name: null-notifications

  - name: discord-notifications
    webhookConfigs:
    - url: http://discord-alm.discord-alm.svc.cluster.local:9094
      sendResolved: true

  route:
    receiver: discord-notifications
    groupBy:
    - alertname
    - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h

    routes:
    # ❌ Drop noise alerts
    - receiver: null-notifications
      matchers:
      - name: alertname
        matchType: =~
        value: "InfoInhibitor|KubeControllerManagerDown|KubeProxyDown|KubeSchedulerDown|NodeClockNotSynchronising|TargetDown"

  inhibitRules:
  # critical inhibits warning/info (ทุก namespace)
  - sourceMatch:
    - name: severity
      value: critical
    targetMatch:
    - name: severity
      matchType: =~
      value: "warning|info"
    equal:
    - namespace
    - alertname

  # warning inhibits info
  - sourceMatch:
    - name: severity
      value: warning
    targetMatch:
    - name: severity
      value: info
    equal:
    - namespace
    - alertname
