apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencti-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: opencti-secret       # name of the k8s Secret to be created
  data:
  - secretKey: app__admin__email
    remoteRef:
      key: initial-secret
      property: OPENCTI_USER

  - secretKey: app__admin__password
    remoteRef:
      key: initial-secret
      property: OPENCTI_PASSWORD

  - secretKey: app__admin__token
    remoteRef:
      key: initial-secret
      property: OPENCTI_TOKEN

  - secretKey: app__alienvault__api_key
    remoteRef:
      key: initial-secret
      property: ALIENVAULT_KEY
