apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface-manager
spec:
  replicas: {{ .Values.replica }}
  revisionHistoryLimit: 1

  selector:
    matchLabels:
      app: interface-manager

  template:
    metadata:
      labels:
        app: interface-manager

    spec:
      containers:
      - name: interface-manager
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always

        command:
          - ruby
          - interface-manager.rb

        ports:
        - containerPort: 8080

        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"

        securityContext:
          runAsUser: 0

        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true

        - name: data
          mountPath: /data

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10

      volumes:
      - name: sys
        hostPath:
          path: /sys

      - name: data
        hostPath:
          path: /data/interface-manager
          type: DirectoryOrCreate
