apiVersion: v1
kind: Service
metadata:
  name: interface-manager-service
  labels:
    app: interface-manager
spec:
  type: ClusterIP
  selector:
    app: interface-manager # ต้องตรงกับ matchLabels ใน Deployment
  ports:
    - name: http
      protocol: TCP
      port: 80       # Port ที่ Service จะเปิดให้คนอื่นเรียก
      targetPort: 8080 # Port ที่แอป Ruby รันอยู่จริงๆ ใน Container
