apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
spec:
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: 80
  type: {{ .Values.nginx.service.type }}
