apiVersion: v1
kind: ConfigMap
metadata:
  name: suricata-script-config
data:
  entrypoint.sh: |
    #!/bin/sh
    set -e

    RULE_FILE="/var/lib/suricata/rules/suricata.rules"
    IFACE=$(ls /sys/class/net | grep -Ev '^(lo|cni|flannel|docker|veth)' | head -n1)


    touch {{ .Values.suricataEth0.logDir }}/suricata.fast.log

    if [ ! -f "$RULE_FILE" ]; then
      echo "[*] Rules not found, running suricata-update..."
      suricata-update
    else
      echo "[*] Rules already exist, skip update"
    fi

    exec suricata -i ${IFACE} -c /etc/suricata/{{ .Values.suricataEth0.suricataConfigName }}
