apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-auditlog-config
data:
  vector.yaml: |
    sources:
      sensor_http:
        type: http_server
        address: 0.0.0.0:8686
        encoding: json

    transforms:
      normalize:
        type: remap
        inputs:
          - sensor_http
        source: |
          del(.headers)

          .cust_ts_yyyy = format_timestamp!(now(), "%Y", timezone: "Asia/Bangkok")
          .cust_ts_mm   = format_timestamp!(now(), "%m", timezone: "Asia/Bangkok")
          .cust_ts_dd   = format_timestamp!(now(), "%d", timezone: "Asia/Bangkok")

          if .AuditType == "API" && exists(.Path) {
            .api = {}

            parsed, err = parse_regex(.Path, r'^/org/(?P<OrgId>[^/]+)/(?P<ApiName>[^/]+)/(?P<Serial>[^/]+)/(?P<Pin>[^/]+)')
            if err == null {
              .api = parsed
              .api.Controller = "ScanItem"
            }
          }

          if .AuditType == "API" {
            .index_name = "pp-" + .cust_ts_yyyy + "-" + .cust_ts_mm + "-" + .cust_ts_dd
          } else if .AuditType == "CloudConnect" {
            .index_name = "cc-" + .cust_ts_yyyy + "-" + .cust_ts_mm + "-" + .cust_ts_dd
          }

          .data = .
          . = {
            "data": .data,
            "index_name": .index_name,
            "@timestamp": now()
          }

    sinks:
      elastic:
        type: elasticsearch
        inputs:
          - normalize
        endpoints:
          - "https://es-censor-es-http.elasticsearch.svc.cluster.local:9200"
        mode: bulk
        compression: gzip

        bulk:
          index: "{{ index_name }}"

        auth:
          strategy: basic
          user: "${ES_USER}"
          password: "${ES_PASSWORD}"

        request:
          concurrency: 4
          timeout_secs: 30

        healthcheck:
          enabled: true

        encoding:
          codec: json
