redis:
  fullnameOverride: redis-etl
  architecture: standalone
  auth:
    enabled: false
  image:
    repository: bitnamilegacy/redis
    # tag: 
  master:
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-crds
