apiVersion: v2
name: helm-misp
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart for MISP (Malware Information Sharing Platform)

dependencies:
  - name: redis
    alias: redis
    condition: redis.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "18.13.0"
  - name: mariadb
    alias: mariadb
    condition: mariadb.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "12.2.9"
  - name: common
    repository: "https://charts.bitnami.com/bitnami"
    version: "2.x.x"
