apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alm-config
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'alm-config-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/rtaf-soc/rtarf-dfn-apps.git
        targetRevision: "{{name}}" #Based on environment
        path: '99-deployments/manifests/alm-config'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-{{name}}.yaml
      destination:
        name: in-cluster
        namespace: monitoring #ให้ลงที่เดียวกับ monitoring
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
