apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatcher-cm
  annotations:
    checksum/config1: {{ .Files.Get "scripts/dispatcher.rb" | sha256sum }}
data:
  dispatcher.rb: |-
{{ .Files.Get "scripts/dispatcher.rb" |  indent 4 }}
