{{- if .Values.misp.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misp-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misp-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi    #20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misp-files-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi    #50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misp-ssl-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misp-gnupg-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: misp-data-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi

{{- end }}