{{- if .Values.misp.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: misp-secrets
type: Opaque
stringData:
  # Replace these values with your secure passwords and keys
  MYSQL_PASSWORD: "mispuserpassword"
  MYSQL_ROOT_PASSWORD: "mariadbpassword"  
  REDIS_PASSWORD: "redispassword"
  ADMIN_PASSWORD: "admin"
  ADMIN_KEY: "YTFiMmMzZDRlNWY2ZzdoOGk5ajBBMUIyQzNENEU1RjZHN0g4STlKMAo" # Base64 encoded + (=)
  ADMIN_ORG_UUID: "5c70da70-2574-4b56-98c9-a7b1adb98b1f"
  ENCRYPTION_KEY: "yourencryptionkey"
  GPG_PASSPHRASE: "yourpassphrase"

{{- end }}