apiVersion: v1
kind: ConfigMap
metadata:
  name: receiver-beat-cm
  annotations:
    checksum/config1: {{ .Files.Get "scripts/receiver-beat.rb" | sha256sum }}
data:
  receiver-beat.rb: |-
{{ .Files.Get "scripts/receiver-beat.rb" |  indent 4 }}
