apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: initial-user-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: initial-user-secret  # name of the k8s Secret to be created
  data:
  - secretKey: INITIAL_USER
    remoteRef:
      key: initial-secret
      property: INITIAL_USER

  - secretKey: INITIAL_PASSWORD
    remoteRef:
      key: initial-secret
      property: INITIAL_PASSWORD
