apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-idp-bootstrap-prod-03 # ใช้วิธีการ rename เพื่อให้ Job ใหม่ถูกสร้างขึ้นและทำงานใหม่ทุกครั้งที่ apply manifest นี้
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: idp-init
          image: asia-southeast1-docker.pkg.dev/its-artifact-commons/please-protect/please-protect-jobs:v0.0.6
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Keycloak to be ready..."
              until [ "$(curl -s -o /dev/null -w '%{http_code}' http://keycloak/health)" = "404" ]; do
                echo "Still waiting..."
                sleep 5
              done
              echo "Keycloak is ready. Running bootstrap..."
              ruby idp-init.rb
          env:
            - name: IDP_URL
              value: "http://keycloak"

            - name: IDP_CLIENT_ID
              value: "pp-api"

            - name: IDP_REALM
              value: "pp-prod"

            - name: IDP_INSECURE_SKIP_VERIFY
              value: "true"

            - name: IDP_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: keycloak-admin-user

            - name: IDP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: keycloak-admin-password

            - name: INITIAL_USER
              valueFrom:
                secretKeyRef:
                  name: initial-user-secret
                  key: INITIAL_USER

            - name: INITIAL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: initial-user-secret
                  key: INITIAL_PASSWORD
