apiVersion: v1
kind: Service
metadata:
  name: misp-redis-service
spec:
  type: ClusterIP
  ports:
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: misp-development
    app.kubernetes.io/name: redis