domain: kafka-ui.rtarf-censor.dev-hubs.com

kafka-ui:
  enabled: true
  fullnameOverride: kafka-ui
  envs:
    config:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      #KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      #KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_READONLY: "false"
      AUTH_TYPE: "DISABLED"
      SECURITY_BASIC_ENABLED: "true"
      SERVER_SERVLET_CONTEXT_PATH: "/tools/kafka-ui"

kafka:
  enabled: true
  fullnameOverride: kafka
  autoCreateTopicsEnable: true

  metrics:
    jmx:
      enabled: true
      containerPorts:
        metrics: 5556
      image:
        repository: bitnamilegacy/jmx-exporter

    service:
      ports:
        metrics: 5556

    serviceMonitor:
      enabled: false   # จัดการเอง

  kraft:
    enabled: true

  extraConfig: |
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    default.replication.factor=1
    min.insync.replicas=1
    auto.create.topics.enable=true

  zookeeper:
    enabled: false

  replicaCount: 1

  controller:
    replicaCount: 1

  listeners:
    client:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT

  persistence:
    enabled: true
    size: 10Gi

  image:
    repository: bitnamilegacy/kafka
