apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.zeekEth0.fullnameOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeek
  template:
    metadata:
      labels:
        app: zeek
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      # ======================
      # Init container
      # ======================
      initContainers:
        - name: fetch-interfaces
          image: curlimages/curl:8.5.0
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e

              IFACE_API="http://interface-manager-service.pp-system.svc.cluster.local/interfaces/enabled"
              HEALTH_API="http://interface-manager-service.pp-system.svc.cluster.local/healthz"

              echo "[*] Waiting for interface-manager..."

              until curl -sf $HEALTH_API >/dev/null; do
                echo "[*] interface-manager not ready..."
                sleep 2
              done

              echo "[*] Fetching interfaces..."

              IFACES=""
              while [ -z "$IFACES" ]; do
                IFACES=$(curl -s $IFACE_API)

                if [ -z "$IFACES" ]; then
                  echo "[*] No interfaces enabled yet..."
                  sleep 2
                fi
              done

              echo "$IFACES" > /shared/interfaces.txt

              echo "[*] Interfaces saved:"
              cat /shared/interfaces.txt

          volumeMounts:
            - name: iface-data
              mountPath: /shared

      containers:
        # ======================
        # Filebeat sidecar
        # ======================
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.12.0
          imagePullPolicy: IfNotPresent

          args:
            - "-e"
            - "-c"
            - "/usr/share/filebeat/filebeat.yml"

          env:
            - name: DUMMY
              value: "{{ .Values.zeekEth0.dummyVar }}"

          securityContext:
            runAsUser: 0

          volumeMounts:
            - name: zeek-logs
              mountPath: {{ .Values.zeekEth0.logDir }}
              readOnly: true

            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml

            - name: filebeat-modules
              mountPath: /usr/share/filebeat/modules.d
              readOnly: true

        # ======================
        # Zeek
        # ======================
        - name: zeek
          image: zeek/zeek:8.0.4
          imagePullPolicy: IfNotPresent

          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_RAW
                - NET_ADMIN
                - IPC_LOCK # อนุญาตให้ทำ Memory Locking
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e
              export ZEEK_LOG_DIR={{ .Values.zeekEth0.logDir }}/current/ens4

              mkdir -p $ZEEK_LOG_DIR
              echo "Log dir = $ZEEK_LOG_DIR"

              exec zeek -i af_packet::ens4 -C local /etc/zeek/site/{{ .Values.zeekEth0.zeeConfigName }} -e "redef AF_Packet::fanout_id = 9;"

          resources:
            requests:
              cpu: {{ .Values.zeekEth0.resources.requests.cpu }}
              memory: {{ .Values.zeekEth0.resources.requests.memory }}
            limits:
              cpu: {{ .Values.zeekEth0.resources.limits.cpu }}
              memory: {{ .Values.zeekEth0.resources.limits.memory }}

          volumeMounts:
            - name: zeek-logs
              mountPath: {{ .Values.zeekEth0.logDir }}

            - name: config-volume
              mountPath: /etc/zeek/site/{{ .Values.zeekEth0.zeeConfigName }}
              subPath: {{ .Values.zeekEth0.zeeConfigName }}

            - name: iface-data
              mountPath: /shared

      volumes:
        - name: zeek-logs
          emptyDir: {}

        - name: config-volume
          configMap:
            name: zeek-config

        - name: filebeat-config
          configMap:
            name: filebeat-config

        - name: filebeat-modules
          configMap:
            name: filebeat-modules

        - name: iface-data
          emptyDir: {}
