apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-basic-authen
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: es-basic-authen       # name of the k8s Secret to be created
  data:
  - secretKey: username
    remoteRef:
      key: initial-secret
      property: ES_USER

  - secretKey: password
    remoteRef:
      key: initial-secret
      property: ES_PASSWORD

  - secretKey: roles
    remoteRef:
      key: initial-secret
      property: ES_ROLE
