domain: opencti.rtarf-censor.dev-hubs.com

### OpenCTI ###
opencti:
  enabled: false
  nameOverride: opencti

  connectors:
  - name: opencti        # Required: unique name
    enabled: true        # Enable the connector
    replicas: 1          # Number of pods
    image:
      repository: opencti/connector-opencti
      tag: 6.9.9
    env:
      CONNECTOR_CONFIDENCE_LEVEL: "80"
      CONNECTOR_ID: "opencti"
      CONNECTOR_UPDATE_EXISTING_DATA: ""
      CONNECTOR_LOG_LEVEL: "info" # Empty use global config
      CONFIG_SECTORS_FILE_URL: ""
      CONFIG_GEOGRAPHY_FILE_URL: ""
      CONFIG_INTERVAL: "3600"
      CONNECTOR_NAME: "OpenCTI"
      CONNECTOR_SCOPE: "marking-definition,identity,location"
      CONNECTOR_TYPE: EXTERNAL_IMPORT
    envFromSecrets:
      OPENCTI_TOKEN:
        name: opencti-secret
        key: app__admin__token

  - name: mitre
    enabled: true
    replicas: 1
    image:
      repository: opencti/connector-mitre
      tag: 6.9.9
    env:
      CONNECTOR_ID: "mitre"
      CONNECTOR_NAME: "MITRE ATT&CK"
      CONNECTOR_SCOPE: "mitre"
      CONNECTOR_TYPE: EXTERNAL_IMPORT
      CONNECTOR_LOG_LEVEL: info
      #CONFIG_INTERVAL: "3600"
    envFromSecrets:
      OPENCTI_TOKEN:
        name: opencti-secret
        key: app__admin__token

  - name: alienvault
    enabled: true
    replicas: 1
    image:
      repository: opencti/connector-alienvault
      tag: 6.9.9
    env:
      CONNECTOR_ID: "alientvault" 
      CONNECTOR_NAME: "AlienVault"  # Optional (default: AlienVault)
      CONNECTOR_SCOPE: "alienvault"  # Optional (default: alienvault)
      CONNECTOR_LOG_LEVEL: "info"  # Optional (default: error)
      CONNECTOR_DURATION_PERIOD: "PT30M"  # Optional (default: PT30M) - ISO8601 Format starting with "P" for Period ex: "PT30M" = Period time of 30 minutes
      ALIENVAULT_BASE_URL: "https://otx.alienvault.com"  # Optional (default: https://otx.alienvault.com)
      ALIENVAULT_X_OPENCTI_SCORE_CRYPTOCURRENCY_WALLET: "80"
    envFromSecrets:
      OPENCTI_TOKEN:
        name: opencti-secret
        key: app__admin__token
      ALIENVAULT_API_KEY:
        name: opencti-secret
        key: app__alienvault__api_key

  - name: misp
    enabled: false #ไว้รอมี MISP_URL แล้วค่อยเปิดใช้งาน
    replicas: 1
    image:
      repository: opencti/connector-misp
      tag: 6.9.9
    env:
      MISP_URL: ""
      MISP_REFERENCE_URL: ""
      MISP_KEY: ""
      MISP_SSL_VERIFY: "false"
      MISP_INTERVAL: "3600"
      MISP_CREATE_INDICATORS: "true"
      MISP_CREATE_OBSERVABLES: "true"
      MISP_CREATE_OBJECT_OBSERVABLES: "true"
      MISP_CREATE_REPORTS: "true"
      MISP_IMPORT_WITH_ATTACHMENTS: "false"
      MISP_IMPORT_ONLY_PUBLISHED: "true"
      MISP_IMPORT_DISTRIBUTION_LEVELS: "0,1,2"
      MISP_IMPORT_THREAT_LEVELS: "1,2,3"
      CONNECTOR_CONFIDENCE_LEVEL: "80"
      CONNECTOR_ID: "misp"
      CONNECTOR_UPDATE_EXISTING_DATA: ""
      CONNECTOR_LOG_LEVEL: "info" # Empty use global config
      CONNECTOR_NAME: "MISP"
      CONNECTOR_SCOPE: "misp"
      CONNECTOR_TYPE: EXTERNAL_IMPORT
    envFromSecrets:
      OPENCTI_TOKEN:
        name: opencti-secret
        key: app__admin__token
  
  worker:
    envFromSecrets:
      OPENCTI_TOKEN:
        name: opencti-secret
        key: app__admin__token

  replicaCount: 1
  envFromSecrets:
    APP__ADMIN__EMAIL:
      name: opencti-secret
      key: app__admin__email

    APP__ADMIN__PASSWORD:
      name: opencti-secret
      key: app__admin__password

    APP__ADMIN__TOKEN:
      name: opencti-secret
      key: app__admin__token

  env:
    APP__BASE_URL: https://opencti.rtarf-censor.dev-hubs.com
    APP__HEALTH_ACCESS_KEY: "ChangeMe"
    ELASTICSEARCH__URL: https://opensearch-cluster-master:9200
    ELASTICSEARCH__SSL__REJECT_UNAUTHORIZED: 'false'
    ELASTICSEARCH__USERNAME: 'admin'
    ELASTICSEARCH__PASSWORD: 'PJskIEk!hsokKE123'

    RABBITMQ__HOSTNAME: "opencti-main-rabbitmq"
    RABBITMQ__USERNAME: opencti
    RABBITMQ__PASSWORD: opencti
    REDIS__HOSTNAME: opencti-main-redis

    MINIO__ENDPOINT: opencti-main-minio
    MINIO__PORT: '9000'
    MINIO__ACCESS_KEY: minioadmin
    MINIO__SECRET_KEY: supersecretpassword
    MINIO__BUCKET_NAME: opencti

  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
  startupProbe:
    enabled: false

  # --- MinIO (internal) ---
  minio:
    enabled: true
    rootUser: minioadmin
    rootPassword: supersecretpassword

    defaultBuckets: "opencti"
    persistence:
      enabled: true
      size: 20Gi
      accessMode: ReadWriteOnce

  # --- Redis (internal) ---
  redis:
    enabled: true
    architecture: standalone

  # --- RabbitMQ (internal) ---
  rabbitmq:
    enabled: true
    auth:
      username: opencti
      password: opencti
    persistence:
      enabled: false

  opensearch:
    enabled: true
    plugins:
      enabled: true
      installList: [ 'ingest-attachment' ]

    extraEnvs:
      - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        value: "PJskIEk!hsokKE123"

    persistence:
      enabled: true
      size: 20Gi
