apiVersion: v2
name: helm-vector-dispatcher
description: A Helm chart for Vector Dispatcher
type: application

version: 0.1.0
appVersion: "0.35.0"

dependencies:
  - name: vector
    version: "0.35.0"
    repository: "https://helm.vector.dev"
    condition: vector.enabled
