apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: opencti
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'opencti-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/rtaf-soc/rtarf-dfn-apps.git
        targetRevision: "{{name}}" #Based on environment
        path: '99-deployments/manifests/opencti'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-{{name}}.yaml
      destination:
        name: in-cluster
        namespace: opencti
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true

