apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pgweb
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'pgweb-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/rtaf-soc/rtarf-dfn-apps.git
        targetRevision: "{{name}}" #Based on environment
        path: '99-deployments/manifests/pgweb'
      destination:
        name: in-cluster
        namespace: pgweb
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
