apiVersion: v1
kind: Service
metadata:
  name: misp-db-service
spec:
  ports:
  - name: tcp-mariadb
    port: 3306
    protocol: TCP
    targetPort: mariadb
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: misp-development
    app.kubernetes.io/name: mariadb
